# Generated by Django 4.2.1 on 2023-05-28 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_musicfile_music_file_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicfile',
            name='protected_file_allowed_emails',
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_file_allowed_emails', models.EmailField(blank=True, max_length=254)),
                ('music_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musicfile')),
            ],
        ),
    ]
